/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef OracleService_CONSTANTS_H
#define OracleService_CONSTANTS_H

#include "OracleService_types.h"

namespace Oracle {

class OracleServiceConstants {
 public:
  OracleServiceConstants();

};

extern const OracleServiceConstants g_OracleService_constants;

} // namespace

#endif
