/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "DataService_constants.h"

namespace TxProtocol {

const DataServiceConstants g_DataService_constants;

DataServiceConstants::DataServiceConstants() {
}

} // namespace

