/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "OracleService_constants.h"

namespace Oracle {

const OracleServiceConstants g_OracleService_constants;

OracleServiceConstants::OracleServiceConstants() {
}

} // namespace

